### PR TITLE
make some changes

### PR DESCRIPTION
**Pull request by teikjun**
testing github actions

### CODE REVIEW

**Comment by teikjun** [comment]
sorry, I made a PR against the wrong repo

**Comment by pdimens** [comment]
@teikjun  Is this an effort to figure out why GitHub Actions is failing on the docs?

**Comment by teikjun** [comment]
@pdimens Yes! I initially thought the issue was because actions@github was mispelled as actions@gihub. But after testing, i found that it wasn't the problem. 
It seems like an issue with `npm ci`, but I'm still looking up how to resolve this

**Comment by pdimens** [comment]
Ah, thank you. I wish I could be more help, but this is quite far out of my skillset. Are others experiencing this error as well?

**Comment by teikjun** [comment]
It's the first reported issue. The documentation for GitHub Actions was added to Docusaurus just a month ago, so there hasn't been other reports yet. 
I'm not familiar with how to fix this either, so I'll let my teammate handle it. Thanks for reporting the issue! :)

**Pull request closed without merging**
